package restaurant;
import java.util.ArrayList;
import java.util.Collections;
import java.util.List;

import agent.Agent;

/** Cashier agent for restaurant.
 *  Keeps a list of checks generated
 *  Receives a check from the waiter
 *  Processes paid checks
 */

public class CashierAgent extends Agent {

	public List<MyCheck> checks = new ArrayList<MyCheck>();

	private String name;
	public Double money;
	
	public CashierAgent(String name) {
		super();
		this.name = name;
		money = 0.0;
	}

	public class MyCheck {
		public Check check;
		public Double amountPaid;

		public MyCheck(Check check){
			this.check = check;
			this.amountPaid = (double) -1;
		}
	}

	// *** MESSAGES ***

	/* Waiter send this message stating a done and a check is given
	 * Added check to list of checks
	 * @param check that is generated by the waiter
	 */
	public void msgGiveCheckToCashier(Check check)
	{
		check.state = Check.CheckState.UNPAID;
		checks.add(new MyCheck(check));
		print("Waiter gives check to Cashier");
		stateChanged();
	}

	/* Customer sends this message that he is paying the check.
	 * It is assumed that the customer is paying a valid amount
	 * @param check that the customer is paying with
	 */
	public void msgPayingCheck(Check check, Double price) {

		for(MyCheck c:checks) {
			if(c.check.equals(check)) {
				c.check.state = Check.CheckState.PAID;
				c.amountPaid = price;
				stateChanged();
				return;
			}
		}
	}

	// *** SCHEDULER ***

	public boolean pickAndExecuteAnAction() {


		for(MyCheck c: checks) {
			if(c.check.state == Check.CheckState.PAID) {
				processCheck(c);
				return true;
			}
		}
		return false;

		// do not care if state is UNPAID or DONE
		// If there exists an order b where status is paid, process b

	}


	// *** ACTIONS ***

	/* Process check and generate change to customer
	 * @param check that is being processed
	 */
	private void processCheck(MyCheck c)
	{
		money += c.amountPaid;
		c.check.state = Check.CheckState.DONE;

		print("Money is now " + money + " with purchase of " + c.amountPaid);
		print("Processing check for Customer");
	}

	/** Returns the name of the cashier 
	 * @return name of cashier */
	public String getName() {
		return name;
	}    
}